#!/bin/bash

# 📍 Resolve absolute path
SOURCE="${BASH_SOURCE[0]:-$0}"
while [ -h "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE"
done
REPO_DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  echo "DESCRIPTION: Start persistent containers started via dcup"
  echo "Usage:"
  echo "  dcstart                        # start containers for current directory"
  echo "  dcstart <proj1> [proj2 ...]    # start containers in multiple projects"
  echo
  echo "Example:"
  echo "  dcstart dev tmp"
  echo "  => starts dev-node-1 and tmp-node-1"
  exit 0
fi

projects=("$@")
[[ ${#projects[@]} -eq 0 ]] && projects+=("$(basename "$PWD")")

for project in "${projects[@]}"; do
  echo "🟢 Starting all containers in project: $project"
  docker compose \
    --file "${REPO_DIR}/docker-compose.yaml" \
    --project-name "$project" \
    start
done

