services:
  node:
    build:
      context: ./node
    image: ${DOCKERHUB_NAMESPACE}/utilcntr-node
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  python:
    build:
      context: ./python
    image: ${DOCKERHUB_NAMESPACE}/utilcntr-python
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  arch:
    build:
      context: ./arch
    image: ${DOCKERHUB_NAMESPACE}/utilcntr-arch
    working_dir: /mnt
    stdin_open: true
    tty: true
    volumes:
      - .:/mnt

  debian:
    build:
      context: ./debian
    image: ${DOCKERHUB_NAMESPACE}/utilcntr-debian
    working_dir: /mnt
    stdin_open: true
    tty: true
    volumes:
      - .:/mnt

