services:
  node:
    build:
      context: ./node
      target: ${DEFAULT_BUILD_TARGET}
      args:
        APP_DIR: ${APP_DIR}
        FILES_DIR: ${FILES_DIR}
    image: ${FULL_IMAGE_TAG}
    working_dir: ${APP_DIR}
    entrypoint: ["dumb-init", "--"]  # ✅ explicitly set entrypoint
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:${APP_DIR}
      - ${APP_DIR}/node_modules
      - /var/run/docker.sock:/var/run/docker.sock  # enable docker passthru
    ports:
      - ${PORT_MAPPINGS:-3000:80}  # 👈 dynamic with fallback
    command: ["sh", "-i"]

  python:
    build:
      context: ./python
      target: ${DEFAULT_BUILD_TARGET}
      args:
        APP_DIR: ${APP_DIR}
        FILES_DIR: ${FILES_DIR}
    image: ${FULL_IMAGE_TAG}
    working_dir: ${APP_DIR}
    entrypoint: ["dumb-init", "--"]  # ✅ explicitly set entrypoint
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:${APP_DIR}
      - /var/run/docker.sock:/var/run/docker.sock  # enable docker passthru
    ports:
      - ${PORT_MAPPINGS:-4000:80}  # 👈 dynamic with fallback
    command: ["sh", "-i"]

  gcc:
    build:
      context: ./gcc
      target: ${DEFAULT_BUILD_TARGET}
      args:
        APP_DIR: ${APP_DIR}
        FILES_DIR: ${FILES_DIR}
    image: ${FULL_IMAGE_TAG}
    working_dir: ${APP_DIR}
    entrypoint: ["dumb-init", "--"]  # ✅ explicitly set entrypoint
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:${APP_DIR}
      - /var/run/docker.sock:/var/run/docker.sock  # enable docker passthru
    ports:
      - ${PORT_MAPPINGS:-5500:80}  # 👈 dynamic with fallback
    command: ["sh", "-i"]

  bash:
    build:
      context: ./bash
      target: ${DEFAULT_BUILD_TARGET}
      args:
        APP_DIR: ${APP_DIR}
        FILES_DIR: ${FILES_DIR}
    image: ${FULL_IMAGE_TAG}
    working_dir: ${APP_DIR}
    entrypoint: ["dumb-init", "--"]  # ✅ explicitly set entrypoint
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:${APP_DIR}
      - /var/run/docker.sock:/var/run/docker.sock  # enable docker passthru
    ports:
      - ${PORT_MAPPINGS:-6000:80}  # 👈 dynamic with fallback
    command: ["sh", "-i"]

  arch:
    build:
      context: ./arch
    image: ${DOCKERHUB_NAMESPACE}/${IMAGE_PREFIX}-arch
    working_dir: ${APP_DIR}
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:${APP_DIR}
      - /var/run/docker.sock:/var/run/docker.sock  # enable docker passthru
