services:
  node:
    image: ${FULL_IMAGE_TAG}
    build:
      context: ./node
      target: ${DEFAULT_BUILD_TARGET}
    # image: ${DOCKERHUB_NAMESPACE}/${IMAGE_PREFIX}-node # only needs this if always uses :latest
    working_dir: /app
    entrypoint: ["dumb-init", "--"]  # ✅ explicitly set entrypoint
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:/app
      - /app/node_modules

  python:
    build:
      context: ./python
    image: ${DOCKERHUB_NAMESPACE}/${IMAGE_PREFIX}-python
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:/app

  arch:
    build:
      context: ./arch
    image: ${DOCKERHUB_NAMESPACE}/${IMAGE_PREFIX}-arch
    working_dir: /mnt
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:/mnt

  debian:
    build:
      context: ./debian
    image: ${DOCKERHUB_NAMESPACE}/${IMAGE_PREFIX}-debian
    working_dir: /mnt
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_WORKDIR:-.}:/mnt

